nextcloud/integration_openai

lib/AppInfo/Application.php, lib/Controller/OpenAiAPIController.php, lib/Service/OpenAiAPIService.php, lib/SpeechToText/STTProvider.php
Here is an STT provider using OpenAI's Whisper API. It supports mp3, mp4, mpeg, mpga, m4a, wav, or webm files as mentioned [there](https://platform.openai.com/docs/api-reference/audio/create).
=> Implement a SpeechToText Provider

CHANGELOG.md, appinfo/info.xml
- Ethical AI rating [#24](https://github.com/nextcloud/integration_openai/issues/24) [#29](https://github.com/nextcloud/integration_openai/issues/29) @marcelklehr
=> Prepare 1.0.11

CHANGELOG.md, appinfo/info.xml
- implement text processing providers (summarize, outline, free prompt and custom reformulate) @julien-nc
- admin setting to choose the API request timeout @julien-nc
- fix scrolling in the picker components @julien-nc
- allow usgin LocalAI without an API key @julien-nc
- save new admin default llm model when switching between OpenAI and LocalAI @julien-nc
=> prepare 1.0.12

CHANGELOG.md, appinfo/info.xml, lib/Service/OpenAiAPIService.php, package-lock.json, package.json
Version bump (and one typo fix) in preparation for the v1.1.0 release.
=> Version bump to v1.1.0

lib/Service/OpenAiAPIService.php
This one slipped through, unfortunately, while rewriting the error handling logic. Psalm would've helped here but it's not yet setup on this repo...
=> Fix transcription

lib/AppInfo/Application.php, lib/Service/OpenAiAPIService.php, lib/TextToImage/TextToImageProvider.php
* We could adjust the expected runtime, not sure about the current values
* the request logic has been extracted from `OpenAiAPIService::createImage` into another method. When running a TextToImage task, we want to trigger the quota stuff but not the image generation mapper stuff as this is done by the assistant
=> Implement a TextToImageProvider

src/components/AdminSettings.vue
| Before | After |
| --- | --- |
| ![grafik](https://github.com/nextcloud/integration_openai/assets/1479486/68b3f805-59a7-49fb-9b5c-87c221521fa5) | ![grafik](https://github.com/nextcloud/integration_openai/assets/1479486/51ae5190-082d-46a9-b5b5-94564fb4ca97) |
=> fix: remove obsolete spacer from admin settings

lib/TextProcessing/HeadlineProvider.php, lib/TextProcessing/ReformulateProvider.php, lib/TextProcessing/SummaryProvider.php, tests/unit/Providers/OpenAiProviderTest.php
Works with popular models >8B. Llama 3 8B fails sometimes, sadly.
=> feat: Allow answering in the same langauge as the input

CHANGELOG.md, appinfo/info.xml
- incorrect numeric settings handling on the server side @julien-nc
- move personal and admin settings to AI sections @julien-nc
- update npm pkgs @julien-nc
=> prepare 2.0.2

CHANGELOG.md, appinfo/info.xml
- Create all task processing providers that were text processing ones + image generation + audio transcription @julien-nc [#102](https://github.com/nextcloud/integration_openai/pull/102)
- ContextWrite provider
- Chat provider
- Add password confirmation when setting sensitive values in user and admin settings
- Drop old image generation, audio transcription and text processing providers
- Use nc/vue 8.14.0
- Fix topics provider output: make it comma separated
=> Prepare 3.0.0

lib/TaskProcessing/TextToImageProvider.php, lib/TaskProcessing/TextToTextProvider.php, lib/TaskProcessing/TranslateProvider.php
* Do no implement useless 'getOptionalOutputShapeDefaults' method
* Use the size param in text2image provider
=> Fix mistakes in some providers

lib/OldProcessing/TextProcessing/FreePromptProvider.php, lib/OldProcessing/TextProcessing/HeadlineProvider.php, lib/OldProcessing/TextProcessing/SummaryProvider.php, lib/OldProcessing/TextToImage/TextToImageProvider.php, lib/TaskProcessing/TextToImageProvider.php
By changing their display name
=> Avoid ambiguity between old and new providers

lib/Controller/OpenAiAPIController.php, lib/Service/OpenAiAPIService.php, tests/bootstrap.php
* Improve test bootstrap
* Don't catch every exception in service::request
=> Small maintenance

lib/AppInfo/Application.php
=> change default image generation size

lib/AppInfo/Application.php, lib/Service/OpenAiAPIService.php, lib/Service/OpenAiSettingsService.php, lib/TaskProcessing/TextToImageProvider.php, src/components/AdminSettings.vue
And show the default size in the label for the optional task type's input field.
=> Add admin setting to set the default image size

package-lock.json, src/components/AdminSettings.vue
Because it applies to all requests to the external API.
=> Move request timeout input out of "text processing" section

README.md, appinfo/info.xml, src/components/AdminSettings.vue
* mention IONOS in the admin settings
* mention IONOS in the README + app description
* fix a few style issues with the recent changes in the global server style.
=> Mention IONOS as service with an OpenAI-compatible API

lib/Service/OpenAiAPIService.php
Use 'user' role for system prompt when o1-* models are used
refs https://github.com/nextcloud/assistant/issues/175
=> Support chatting with o1 models

lib/Settings/Admin.php, src/components/AdminSettings.vue
=> Add a warning if the assistant app is not installed

composer.lock, lib/Service/OpenAiAPIService.php, src/components/AdminSettings.vue, vendor-bin/php-cs-fixer/composer.lock, vendor-bin/phpunit/composer.lock, vendor-bin/psalm-phar/composer.lock
=> fix: prevent error log flood when not configured

lib/Service/OpenAiSettingsService.php
Noticed some mistakes in the phpdoc while working on #210
=> Fix: phpdoc is incorrect

src/components/AdminSettings.vue
Found by @nickvergessen in https://github.com/nextcloud/integration_watsonx/pull/6.
=> fix(l10n): fix English source string

package-lock.json, package.json, src/adminSettings.js, src/components/AdminSettings.vue, src/components/PersonalSettings.vue, src/personalSettings.js
RCs are available for `@nextcloud/vue` v9 that uses Vue 3.
There are many things to adjust. I think I covered everything.
=> Migrate to Vue 3 and @nextcloud/vue 9

lib/Service/OpenAiAPIService.php
=> fix: improve 401 error message

src/components/QuotaPeriodPicker.vue
=> i18n: context needed for the quota reset day

lib/Migration/Version030102Date20241003155512.php, lib/Migration/Version030103Date20241009172829.php, lib/Service/OpenAiAPIService.php, lib/Service/OpenAiSettingsService.php, lib/TaskProcessing/AnalyzeImagesProvider.php, lib/TaskProcessing/AudioToAudioChatProvider.php, lib/TaskProcessing/AudioToTextProvider.php, lib/TaskProcessing/ChangeToneProvider.php, lib/TaskProcessing/ContextWriteProvider.php, lib/TaskProcessing/EmojiProvider.php, lib/TaskProcessing/HeadlineProvider.php, lib/TaskProcessing/ProofreadProvider.php, lib/TaskProcessing/ReformulateProvider.php, lib/TaskProcessing/SummaryProvider.php, lib/TaskProcessing/TextToImageProvider.php, lib/TaskProcessing/TextToSpeechProvider.php, lib/TaskProcessing/TextToTextChatProvider.php, lib/TaskProcessing/TextToTextChatWithToolsProvider.php, lib/TaskProcessing/TextToTextProvider.php, lib/TaskProcessing/TopicsProvider.php, lib/TaskProcessing/TranslateProvider.php
The only values that are not stored or loaded lazily are the ones we always read in Application.php.
=> Lazy load most app config values, store them as lazy too
