- lib/AppInfo/Application.php
- lib/Service/OpenAiAPIService.php
- lib/Translation/TranslationProvider.php
Implement `ITranslationProvider` and `IDetectLanguageProvider`.
Tested with https://github.com/nextcloud/spreed/pull/9512
> Add translation provider

- CHANGELOG.md
- appinfo/info.xml
- try to select gpt-3.5 when default model is not found when getting model list
- use selected default llm (in admin settings ) in the translation provider
- remove dashboard category in info.xml
- dynamically change labels depending if OpenAi or LocalAi is used
> Prepare v1.0.13

- lib/Controller/OpenAiAPIController.php
- lib/Service/OpenAiAPIService.php
- lib/Service/OpenAiSettingsService.php
- src/components/AdminSettings.vue
- src/components/PersonalSettings.vue
Exposes choosing the endpoint for the LocalAI as an admin setting. This should improve text generations quite a bit since the chat endpoint will inject the proper model specific prompt template at the LocalAI end.
Also, fixes the params for calling the plain "completions" endpoint: https://github.com/nextcloud/integration_openai/issues/60
> Add admin setting for choosing endpoint when using LocalAI

- appinfo/info.xml
- lib/TextProcessing/FreePromptProvider.php
- lib/TextProcessing/HeadlineProvider.php
- lib/TextProcessing/ReformulateProvider.php
- lib/TextProcessing/SummaryProvider.php
* Bump min NC version to 28 (when the new interfaces appeared
* Bump max NC version to 29 (not necessary but why not)
* Set an expected time of 10 seconds if OpenAI is used and 5 minutes if LocalAI is used
@marcelklehr Is it fine if `setUserId` overwrites the injected value in the class attribute?
> Implement IProviderWithExpectedRuntime and IProviderWithUserId TP providers

- lib/Service/OpenAiAPIService.php
- tests/unit/Controller/OpenAiControllerTest.php
So far, to use LocalAI, one had to set `"allow_local_remote_servers": true` in `config.php`. 
However, I think this should not be a requirement for a service that is meant to run in the local network?
This PR adjusts the request to allow local addresses when using LocalAI, without a need to allow requests to local addresses for all other apps.
> Allow local IP address for LocalAI

- lib/AppInfo/Application.php
- lib/Service/OpenAiAPIService.php
- lib/TextProcessing/FreePromptProvider.php
- lib/TextProcessing/HeadlineProvider.php
- lib/TextProcessing/ReformulateProvider.php
- lib/TextProcessing/SummaryProvider.php
- lib/TextToImage/TextToImageProvider.php
- tests/unit/Controller/OpenAiControllerTest.php
Adds low-pass filtering for the expected runtime based on observed runtimes so that the consumers of the providers can have a more accurate estimate of the runtime.
> Use lp-filtering to estimate expected runtime

- lib/AppInfo/Application.php
- lib/Controller/OpenAiAPIController.php
- lib/Service/OpenAiAPIService.php
- lib/TextProcessing/FreePromptProvider.php
- lib/TextToImage/TextToImageProvider.php
- tests/unit/Controller/OpenAiControllerTest.php
- tests/unit/Providers/OpenAiProviderTest.php
closes https://github.com/nextcloud/text2image_helper/issues/49
Auth is not an issue with OpenAI as result image URLs are accessible publicly.
But when LocalAI is set up with basic auth, we still don't use any auth when getting result images.
Tested with LocalAI behind a reverse proxy adding basic auth.
> Fix: use basic auth to get generated images if necessary

- lib/Service/OpenAiAPIService.php
- lib/Service/OpenAiSettingsService.php
- src/components/AdminSettings.vue
Before we get dynamic parameters in AI providers, it's still nice to be able to manually set extra parameters for the completion request.
> Allow admins to set extra params for completion requests

- README.md
- appinfo/info.xml
- lib/AppInfo/Application.php
- lib/Service/OpenAiAPIService.php
- lib/Service/OpenAiSettingsService.php
- lib/TextProcessing/FreePromptProvider.php
- lib/TextProcessing/HeadlineProvider.php
- lib/TextProcessing/ReformulateProvider.php
- lib/TextProcessing/SummaryProvider.php
- lib/TextToImage/TextToImageProvider.php
- lib/Translation/TranslationProvider.php
- src/components/AdminSettings.vue
- tests/unit/Providers/OpenAiProviderTest.php
* use nextcloud/vue components instead of pure html inputs
* adjust labels so it's clear that the service URL can point to any service with an OpenAI-like API
* adjust README and info.xml to make it more explicit which services this app is compatible with, mention Plusserver
* add "service name" admin setting which is then used by all the providers so the AI provider selection (in AI admin settings) is clearer
* allow admins to toggle each provider
* reorganize admin settings subsections, group text processing stuff in a new subsection
| before | after |
|---|---|
|  ![image](https://github.com/nextcloud/integration_openai/assets/11291457/a5313bcc-a6b5-4caf-93f1-76473eb5cc78) | ![image](https://github.com/nextcloud/integration_openai/assets/11291457/8445c1c5-756e-4141-a3ef-f876e09b86ca) | …
> Refresh admin settings

- CHANGELOG.md
- allow admins to set extra params for completion requests @julien-nc [#86](https://github.com/nextcloud/integration_openai/pull/86)
- new "service name" admin setting @julien-nc [#87](https://github.com/nextcloud/integration_openai/pull/87)
- mention compatibility with Plusserver in README and app description @julien-nc [#87](https://github.com/nextcloud/integration_openai/pull/87)
- make it possible to toggle image, text and stt providers in admin setting @julien-nc [#87](https://github.com/nextcloud/integration_openai/pull/87)
- support NC 30
- remove smart pickers that are now provided by the assistant app @julien-nc [#85](https://github.com/nextcloud/integration_openai/pull/85)
- use nextcloud/vue components in admin settings @julien-nc …
> Prepare 2.0.0

- CHANGELOG.md
- appinfo/info.xml
- support MistralAI API @julien-nc
- only add user param in chat completion request if using openAI @julien-nc
- allow empty string for extra llm params @julien-nc
- safely drop indexes in last migration step @julien-nc [#95](https://github.com/nextcloud/integration_openai/issues/95)
- fix mistake when getting extra model params @julien-nc [#94](https://github.com/nextcloud/integration_openai/issues/94)
> prepare 2.0.1

- lib/Service/OpenAiSettingsService.php
- src/components/AdminSettings.vue
Arbitrary choice to use null to know when we should delete a setting value.
`parseInt` returns `NaN` with invalid values, this becomes `null` in the network request.
This should be pretty safe.
> Fix incorrect numeric settings handling on the server side

- CHANGELOG.md
- appinfo/info.xml
- Translation provider for the task processing API @julien-nc [#111](https://github.com/nextcloud/integration_openai/pull/111)
- Adjust providers to changes in server (enum values and defaults) @julien-nc [#111](https://github.com/nextcloud/integration_openai/pull/111)
- Drop the old translation provider @julien-nc [#111](https://github.com/nextcloud/integration_openai/pull/111)
> Prepare 3.0.1

- CHANGELOG.md
- appinfo/info.xml
- admin-settings: add image model selection dropdown @kyteinsky [#122](https://github.com/nextcloud/integration_openai/pull/122)
- bump max NC version to 31, update composer dev dependencies @julien-nc
- Bring back textProcessing, translation, STT, and image generation providers @julien-nc [#120](https://github.com/nextcloud/integration_openai/pull/120)
- Avoid ambiguity between old and new providers @julien-nc [#121](https://github.com/nextcloud/integration_openai/pull/121)
- fix(TextToText,Translate): Don't throw in getOptionalInputShapeEnumValues @marcelklehr [#115](https://github.com/nextcloud/integration_openai/pull/115)
- fix(providers): do no implement useless 'getOptionalOutputShapeDefaults' method, use the size param in text2image provider @julien-nc …
> prepare 3.1.0

- lib/AppInfo/Application.php
- lib/Controller/ConfigController.php
- lib/OldProcessing/TextToImage/TextToImageProvider.php
- lib/Service/OpenAiAPIService.php
- lib/TaskProcessing/ContextWriteProvider.php
- lib/TaskProcessing/HeadlineProvider.php
- lib/TaskProcessing/ReformulateProvider.php
- lib/TaskProcessing/SummaryProvider.php
- lib/TaskProcessing/TextToImageProvider.php
- lib/TaskProcessing/TextToTextProvider.php
- lib/TaskProcessing/TopicsProvider.php
- lib/TaskProcessing/TranslateProvider.php
- src/components/AdminSettings.vue
- src/components/PersonalSettings.vue
* Cleanup admin and user settings
* Consider all credential/urls as sensitive
* Always save default models after getting them when credentials/URL have changed
* Fix default model enum values in TaskProcessing providers
* Harmonize default model selection between text and image generation
* Add "model" optional input shape in all text and image generation task types
* Make sure default models are saved if they are not up-to-date when browsing the admin settings (cc @szaimen)
closes #129
> Fix and clarify default models

- CHANGELOG.md
- appinfo/info.xml
- Ability to choose model in the assistant for most providers @julien-nc [#130](https://github.com/nextcloud/integration_openai/pull/130)
- Switch from webpack to vite @julien-nc [#131](https://github.com/nextcloud/integration_openai/pull/131)
- Fix admin settings not saving the models in some cases @julien-nc [#130](https://github.com/nextcloud/integration_openai/pull/130)
> Prepare 3.1.1

- CHANGELOG.md
- appinfo/info.xml
- Simple cache for model list to speed up provider loading @julien-nc [#133](https://github.com/nextcloud/integration_openai/pull/133)
- Change default image generation size @kyteinsky [#124](https://github.com/nextcloud/integration_openai/pull/124)
> Prepare 3.1.2

- appinfo/info.xml
- lib/AppInfo/Application.php
- lib/Controller/ConfigController.php
- lib/Cron/CleanupQuotaDb.php
- lib/Migration/Version030102Date20241003155512.php
- lib/Migration/Version030103Date20241009172829.php
- lib/Service/OpenAiAPIService.php
- lib/Service/OpenAiSettingsService.php
- lib/TaskProcessing/ContextWriteProvider.php
- lib/TaskProcessing/HeadlineProvider.php
- lib/TaskProcessing/ReformulateProvider.php
- lib/TaskProcessing/SummaryProvider.php
- lib/TaskProcessing/TextToImageProvider.php
- lib/TaskProcessing/TextToTextChatProvider.php
- lib/TaskProcessing/TextToTextProvider.php
- lib/TaskProcessing/TopicsProvider.php
- lib/TaskProcessing/TranslateProvider.php
- tests/unit/Providers/OpenAiProviderTest.php
So we can mark some values as sensitive and the encryption is handled by the core.
I left out the "old" providers because we can now get rid of them (as TaskProcessing providers can be used by the old APIs).
Also, I didn't use the getValueInt and setValueInt methods because I don't know how it behaves when the value stored in db is an empty string so I was afraid it would mess with the default values and too lazy to try and check how it behaves.
> Switch to IAppConfig

- lib/AppInfo/Application.php
- lib/Migration/Version030104Date20241011192830.php
- lib/Service/OpenAiAPIService.php
- src/components/AdminSettings.vue
> feat: add ability to customize API root path in service URL

- lib/TaskProcessing/ContextWriteProvider.php
- lib/TaskProcessing/HeadlineProvider.php
- lib/TaskProcessing/ReformulateProvider.php
- lib/TaskProcessing/SummaryProvider.php
- lib/TaskProcessing/TextToTextChatProvider.php
- lib/TaskProcessing/TextToTextProvider.php
- lib/TaskProcessing/TopicsProvider.php
- lib/TaskProcessing/TranslateProvider.php
Since the provider's process method is called in a bg job, there is no userId injected in the constructors. That's why we have a userId param in the process method.
It was not a blocking problem because the quota check is successful when the userId is null. But still it was not checking the quota correctly.
> Fix: Use correct userId in most provider

- lib/Service/OpenAiAPIService.php
closes #138
If OpenAI is not used and the app is configured with an API key, use it when retrieving images.
This is a smaller alternative to #141. We can keep #141 (after removing the api-key-related changes) since it contains other improvements.
> Fix: Use api key in image retrieval request

- lib/AppInfo/Application.php
- lib/Service/OpenAiAPIService.php
- lib/Service/OpenAiSettingsService.php
- tests/unit/Providers/OpenAiProviderTest.php
Closes #146
I assume all user have access to the same models so there is a global cache. @kyteinsky Do you think it's likely that users have access to different models? I'm asking because they can set a different API key/credentials.
> Cache the models for 30min in distributed cache

- CHANGELOG.md
- appinfo/info.xml
- Admin setting to choose transcription model @julien-nc [#154](https://github.com/nextcloud/integration_openai/pull/154)
- Admin setting to set the default image size @julien-nc [#135](https://github.com/nextcloud/integration_openai/pull/135)
- Add ability to customize API root path in service URL @edward-ly [#143](https://github.com/nextcloud/integration_openai/pull/143)
- Encrypt api keys and basic passwords for app config and user settings @julien-nc [#136](https://github.com/nextcloud/integration_openai/pull/136) [#139](https://github.com/nextcloud/integration_openai/pull/139)
- Remove old providers since old APIs can use TaskProcessing providers @julien-nc [#140](https://github.com/nextcloud/integration_openai/pull/140)
- Cache the models for 30min in distributed cache @julien-nc …
> Prepare 3.2.0

- lib/TaskProcessing/HeadlineProvider.php
- tests/unit/Providers/OpenAiProviderTest.php
resolves #161 
copied from https://github.com/nextcloud/llm2/blob/main/lib/headline.py#L30
> fix: English headlines for English text with OpenAI

- .github/workflows/psalm.yml
- appinfo/routes.php
- composer.json
- composer.lock
- lib/AppInfo/Application.php
- lib/Controller/ConfigController.php
- lib/Controller/OpenAiAPIController.php
- lib/OldProcessing/Translation/TranslationProvider.php
- lib/Service/OpenAiAPIService.php
- lib/Service/OpenAiSettingsService.php
- lib/TaskProcessing/ChangeToneProvider.php
- lib/TaskProcessing/ContextWriteProvider.php
- lib/TaskProcessing/HeadlineProvider.php
- lib/TaskProcessing/ReformulateProvider.php
- lib/TaskProcessing/TextToTextChatProvider.php
- lib/TaskProcessing/TextToTextChatWithToolsProvider.php
- lib/TaskProcessing/TextToTextProvider.php
- lib/TaskProcessing/TopicsProvider.php
- lib/TaskProcessing/TranslateProvider.php
- vendor-bin/php-cs-fixer/composer.lock
- vendor-bin/phpunit/composer.lock
This will be used by the Agency feature which uses the tooling capabilities of LLMs.
This provider can be tested in the assistant because it dynamically generates a form for the task type (we will hide this task type later).
One small issue: We enforce all the input params but we might wanna set the tool_message (The result of tool calls in the last interaction).
If we give a fake/useless value to the OpenAI API, the request fails because the tool_message does not come after a "tool call" message.
To be discussed.
To test this provider, just replace `$toolMessage = $input['tool_message'];` by `$toolMessage = null;` in the provider and pass a dummy tool_message value in the form.
As all input fields have to be defined, also add at least one message in the "chat history".
You can use that …
> Add ChatWithTools provider

- lib/AppInfo/Application.php
- lib/Service/OpenAiSettingsService.php
- lib/TaskProcessing/SummaryProvider.php
- src/components/AdminSettings.vue
- tests/unit/Providers/OpenAiProviderTest.php
Closes #150. Lightly tested with gpt-4o, gpt-4o-mini, and gpt-3.5-turbo.
> feat: add input chunking to summarize task

- CHANGELOG.md
- appinfo/info.xml
- Change tone task type + provider @janepie [#163](https://github.com/nextcloud/integration_openai/pull/163)
- Proofread provider @janepie [#169](https://github.com/nextcloud/integration_openai/pull/169)
- ChatWithTools provider @julien-nc [#167](https://github.com/nextcloud/integration_openai/pull/167)
- Add ability to summarize by chunks @edward-ly [#157](https://github.com/nextcloud/integration_openai/pull/157)
- Fix headline prompt @janepie [#162](https://github.com/nextcloud/integration_openai/pull/162)
- Grammar mistake @rakekniven [#165](https://github.com/nextcloud/integration_openai/pull/165)
> prepare 3.3.0

- composer.lock
- lib/Service/OpenAiAPIService.php
- lib/Service/OpenAiSettingsService.php
- src/components/AdminSettings.vue
- tests/unit/Providers/OpenAiProviderTest.php
- vendor-bin/php-cs-fixer/composer.lock
- vendor-bin/phpunit/composer.lock
* Use max_completion_tokens instead of deprecated max_tokens by default
* Add admin option to choose
When using OpenAI with o1 models, the deprecated max_tokens param is rejected and the request fails with
`Unsupported parameter: 'max_tokens' is not supported with this model.`
All good with the new `max_completion_tokens` param.
We keep the option to use the deprecated one as I assume many other services didn't adjust that yet.
refs https://github.com/nextcloud/assistant/issues/175
> Use max_completion_tokens instead of deprecated max_tokens

- lib/Service/OpenAiAPIService.php
Do not attempt to update local quota if chat/completion response does not have usage.total_tokens set
> Fix crash when quota info is missing from completion response

- lib/AppInfo/Application.php
- src/components/AdminSettings.vue
Due to compatibility reasons, the default size should be set to 1024
- dall-e 2 can work with 512
but
- dall-e 3 can only work > 1024
https://platform.openai.com/docs/guides/images#size-and-quality-options
- IONOS can only work >1024
https://api.ionos.com/docs/inference-openai/v1/#tag/OpenAI-Compatible-Endpoints/operation/openaiCompatImagesGenerationsPost
so to make it compatible with the most, it should be adopted
> Raise the default image size for compatibility

- lib/Service/OpenAiAPIService.php
> feat: add support for together ai

- CHANGELOG.md
- appinfo/info.xml
- Add support for together ai @kyteinsky [#197](https://github.com/nextcloud/integration_openai/pull/197)
- Enable use_max_completion_tokens_param by default for OpenAI, disable by default for non-OpenAI @julien-nc [#184](https://github.com/nextcloud/integration_openai/pull/184)
- Add admin setting to toggle authentication in the image retrieval request @julien-nc [#186](https://github.com/nextcloud/integration_openai/pull/186)
- Add a warning in the admin settings if the assistant app is not installed @julien-nc [#185](https://github.com/nextcloud/integration_openai/pull/185)
- Raise the default image size for compatibility @Rello [#193](https://github.com/nextcloud/integration_openai/pull/193)
- Bump max NC version to 32
- Prevent browser autocomplete for API key inputs and credentials …
> Prepare 3.5.0

- README.md
Was asked about configuring various AI things. That you have to set up things in Connected Accounts wasn't really obvious.
> Update README with more config info

- lib/TaskProcessing/SummaryProvider.php
- tests/unit/Providers/OpenAiProviderTest.php
Resolves #209 (or at least, that is the goal). A variation of this prompt has been tested to work on Gemma 3 12B along with several of the GPT models, but that is admittedly still not exhaustive by any means.
> fix(TaskProcessing): update summary prompt

- AUTHORS.md
- README.md
- appinfo/info.xml
- composer.lock
- lib/AppInfo/Application.php
- lib/Service/OpenAiAPIService.php
- lib/Service/OpenAiSettingsService.php
- lib/TaskProcessing/SummaryProvider.php
- lib/TaskProcessing/TextToSpeechProvider.php
- lib/TaskProcessing/TextToSpeechTaskType.php
- src/components/AdminSettings.vue
- tests/unit/Providers/OpenAiProviderTest.php
- vendor-bin/php-cs-fixer/composer.lock
- vendor-bin/phpunit/composer.lock
- vendor-bin/psalm-phar/composer.lock
This creates an implementation for text to speech. (https://github.com/nextcloud/server/pull/52051)
I don't really know for sure what to do about the voices because I couldn't find an endpoint that lists the voices. Right now its just hardcoded to one of openai's voices. Some ideas that I have are:
1. Make the input field text for the voice and just fail when an invalid voice is given
2. Detect when open ai endpoint is being used and then use hardcoded list
3. Let admin create a list of valid values to use
Openai's documentation for text to speech: https://platform.openai.com/docs/guides/text-to-speech#voice-options
> feat(Text2Speech): Add support for text to speech

- .github/workflows/appstore-build-publish.yml
- .github/workflows/lint-eslint.yml
- .github/workflows/lint-php-cs.yml
- .github/workflows/lint-php.yml
- .github/workflows/node.yml
- .github/workflows/phpunit-mariadb.yml
- .github/workflows/phpunit-pgsql.yml
- .github/workflows/pr-feedback.yml
- .github/workflows/psalm-matrix.yml
- .github/workflows/reuse.yml
- tests/bootstrap.php
Went through and copied all workflows from templates to see if it fixes unit tests. Did need to remove the  --no-scripts flag from the install dependencies step.
> Update all workflows

- lib/Service/OpenAiAPIService.php
Turns out that some providers like google don't just return `application/json`, but also add the character encoding after it breaking the content type detection. Ex: `application/json; charset=utf-8`
> fix: content type identification

- src/components/AdminSettings.vue
- src/components/PersonalSettings.vue
For the vue3 migration, it looks like `NcInputField` and `NcTextField` need icon slots now.
> feat: use outline icons instead of solid ones

- lib/Service/OpenAiSettingsService.php
instead of deleting one key that we don't use anymore.
> Invalidate all cache with a prefix

- lib/Service/ChunkService.php
- lib/TaskProcessing/ChangeToneProvider.php
- lib/TaskProcessing/ContextWriteProvider.php
- lib/TaskProcessing/ProofreadProvider.php
- lib/TaskProcessing/ReformulateProvider.php
- lib/TaskProcessing/SummaryProvider.php
- lib/TaskProcessing/TopicsProvider.php
- lib/TaskProcessing/TranslateProvider.php
- tests/unit/Providers/OpenAiProviderTest.php
The implementation for TopicsProvider isn't that great, but is passable.
Also I added progress to all the chunked providers because it made debugging easier.
> feat: add chunking to ChangeTone, ContextWrite, ProofreadProvider, ReformulateProvider, TopicsProvider, and TranslateProvider

- src/components/AdminSettings.vue
Mistake that was forgotten when #210 was updated for vue 3
> fix: default tts model selector

- .eslintrc.cjs
- lib/AppInfo/Application.php
- lib/Cron/CleanupQuotaDb.php
- lib/Db/QuotaUsageMapper.php
- lib/Service/OpenAiAPIService.php
- lib/Service/OpenAiSettingsService.php
- src/components/AdminSettings.vue
- src/components/PersonalSettings.vue
- src/components/QuotaPeriodPicker.vue
This does the minimum to fix this adding a monthly option for period that resets every month or exact multiple of months. This could also be used for yearly as long as a start date of January is ok. The date range was originally planned to be put into the admin settings, but I think it looks better in personal settings.
Resolves part of: #250
> feat: add monthly quota periods

- appinfo/info.xml
- appinfo/routes.php
- lib/AppInfo/Application.php
- lib/Controller/QuotaRuleController.php
- lib/Db/QuotaRule.php
- lib/Db/QuotaRuleMapper.php
- lib/Db/QuotaUsageMapper.php
- lib/Db/QuotaUser.php
- lib/Db/QuotaUserMapper.php
- lib/Migration/Version030800Date20250812122830.php
- lib/Service/OpenAiAPIService.php
- lib/Service/OpenAiSettingsService.php
- lib/Service/QuotaRuleService.php
- lib/Settings/Admin.php
- src/components/AdminSettings.vue
- src/components/PersonalSettings.vue
- src/components/QuotaPeriodPicker.vue
- src/components/Rules/MultiselectWho.vue
- src/components/Rules/QuotaRules.vue
- src/components/Rules/Rule.vue
- tests/unit/Providers/OpenAiProviderTest.php
- tests/unit/Quota/QuotaTest.php
Adds quota rules that allow you to set a quota for user/group and combinations of them including pools (where quota is shared among a collection of users/groups)
Resolves: #149
> feat: Implement quota rules

- appinfo/routes.php
- lib/Controller/QuotaRuleController.php
- lib/Cron/CleanupQuotaDb.php
- lib/Db/QuotaUsageMapper.php
- lib/Service/OpenAiSettingsService.php
- lib/Service/QuotaRuleService.php
- lib/Settings/Admin.php
- src/components/AdminSettings.vue
Resolves: #250 
Currently downloads a csv that looks like the sample below sorted by usage which is why it currently requires filtering the category:
[quota_usage.csv](https://github.com/user-attachments/files/21903953/quota_usage.csv)
Also does double count usage if used in a pool then it counts for the user and the pool in the report. Ex: users alice and bob are in a pool. Alice used 20 tokens, bob 300 tokens. The csv would look like this
User | Usage
-- | --
Pool for Rule 1 | 320
Bob | 300
Alice | 20
> Feat: quota report download

- appinfo/info.xml
- lib/Controller/OpenAiAPIController.php
- lib/Cron/RefreshModels.php
- lib/Migration/Version030900Date20251006152735.php
- lib/Service/OpenAiAPIService.php
closes #272
This prevents the model list to be obtained with a network request to the external service when populating the enum values of the task processing providers (which is a problem when the remote service is unreachable).
We now store the model list in a permanent storage (the DB) and it is only refreshed:
* when the settings page is accessed
* on upgrade to 3.9.0
* once a day in a bg job
> Store the model list in the DB
